testMode = false
autoSwitchLanguage = false
autoDownloadVMTranslationPack = false
translationPackSource = "GITEE"
checkModPackTranslationUpdate = false
i18nUpdateModCheck = true
vaultPatcherCheck = true
